# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-23 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='logo',
            field=models.ImageField(upload_to=''),
        ),
    ]
